# baseURL = "http://example.com/"
languageCode = "en-us"
title = "Restaurant La Senna"
theme = "resto-hugo"
copyright = "</> with <3 by <a target='_blank' href='https://alesc.dev'>alesc.dev</a>" # HTML tags supported
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

# Theme specific configuration
[params]
logo = "img/logo.svg"
enableDisqus = false # enable / disable comments for blog posts
enableGA = false # enable / disable google analytics
heroText = "Descopera <br> Povestea Noastra !"
footerText = "This area supports HTML code. Text can be edited with <code>footerText</code> value in config.toml"
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"