# baseURL = "http://example.com/"
languageCode = "ro"
title = "Restaurant La Senna"
theme = "resto-hugo"
disableKinds = ["taxonomy", "taxonomyTerm"]
defaultContentLanguage = "ro"
disableHugoGeneratorInject = "true"
copyright = "<i class='subheading fas fa-code'></i> with <i class='subheading fas fa-heart'></i> by <a target='_blank' href='https://alesc.dev'>alesc.dev</a>" # HTML tags supported
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

# Theme specific configuration
[params]
logo = "img/logo.png"
enableDisqus = false # enable / disable comments for blog posts
enableGA = false # enable / disable google analytics
heroText = "Restaurant <br> La Senna"
footerText = "Ramai la curent cu toate noutatile Restaurantului La Senna urmarindu-ne pe retelele de socializare!"
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"